### PR TITLE
29 create backend communication interface

### PR DESCRIPTION
**Pull request by parslie**
We created functions that interface the REST-APIs endpoints.

**NOTE:** We haven't rebased yet, so that needs to be done before merging.

### CODE REVIEW

**Review by jakob123100 — CHANGES_REQUESTED** [review]
Looks to be on the right track functionally and implements other parts of the system well. Nice work!

Some feedback,

- [x] The branch contains idea files which should be removed.
- [x] The backend_communication.py script should be updated a bit to conform to pep8 guidelines. Lines 77, 80 and 87 are over 79 characters long. The File does not a contain a docstring at the top.
- [x] The import from backend_communication import * in src/calculate_dependencies.py should use python module structure. Example from src.backend_communication (the dot is important here, might work with just .backend_communication not entirely sure.)

Recommendations,

- You might want to consider using a for each loop instead of for i in range to increase readability.

**Comment by jakob123100** [comment]
Also the the util import in backend_communication.py need to have a dot aswell. Ie `from .util import Dependency`

**Review by jakob123100 — APPROVED** [review]
Looks good!

**Review by grufe — APPROVED** [review]
Looks good! 

There were a few linter errors in backend_communication.py
- line 40 (missing-timeout)
- line 57 (redefined-builtin)
- line 68 (trailing-whitespace)

Lint message:
backend_communication.py:68:24: C0303: Trailing whitespace (trailing-whitespace)
backend_communication.py:40:8: W3101: Missing timeout argument for method 'requests.post' can cause your program to hang indefinitely (missing-timeout)
backend_communication.py:57:13: W0622: Redefining built-in 'id' (redefined-builtin)

**Pull request merged**
